Unified the formatting and added rail road diagrams
UPPAALModelChecker/docs.uppaal.org pull request #39
Opened 2023-06-01 15:58 UTC by mikucionisaau

- [x] reformatted most of the example code to be consistent
- [x] added [rail road diagrams](https://www.bottlecaps.de/rr/ui) for syntax (grammar.txt contains the massaged syntax)
- [ ] fixed some spelling issues and other minor updates

2023-06-02 08:50 UTC, thorulf4 requested changes

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +: computes a collaborative strategy, i.e. finds a reachable state from where a safe strategy is found: `safe` state predicate is maintained to always remain true no matter what the oponent/environmen
This description didn't really explain the query to me, i've tried to change the sentence to highlight what i experienced/suprised me while testing this query type
```suggestion
: Checks if opponent and player can work together and reach one of the winning states of a given control strategy, note that the state predicate `safe` must always be true before reaching a winning state and is guaranteed to remain true after reaching winning state.

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +: computes a safe strategy by observing only the state of the specified predicate expressions.
```suggestion
: computes a safety strategy where the player can only observe the state of the specified predicate expressions.
```

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +`{ x<=5, Gate.Idle, Gate.Occ }: A[] safe`
This line doesn't match the CFG given above.
By looking at the PartialControlSpecifier I expect the syntax:
`{ x<=5, Gate.Idle, Gate.Occ } control: A[] safe`

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +: computes a safe strategy but only up until the `goal` is reached.
```suggestion
: computes a safety strategy but only up until the `goal` is reached.
```

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +: (weakly until the `goal`) either a safe strategy is found or a safe strategy holds until the goal is reached.
```suggestion
: (weakly until the `goal`) either a safety strategy is found or a safety strategy holds until the goal is reached.
```

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
>  : compute a strategy where `safe` state predicate is always true no matter what the oponent/environment chooses to do. The strategy is *permissive* in a sense that for a given state the strategy may
```suggestion
: compute a strategy where `safe` state predicate is always true no matter what the opponent/environment chooses to do. The strategy is *permissive* in a sense that for a given state the strategy may propose multiple actions for the player/controller. Such permissive strategy can be thought of as a union of all strategies satisfying the predicate, therefore it does not have any notion of progress and may include infinite loops.
```

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/system-description/declarations/types.md
> +Meta variables are stored outside of the state vector and are sematically not considered part of the state. I.e. two states that only differ in meta variables are considered to be equal.
```suggestion
Meta variables are stored outside of the state vector and are semantically not considered part of the state. I.e. two states that only differ in meta variables are considered to be equal.
```

2023-06-02 08:50 UTC, thorulf4 commented on content/language-reference/system-description/templates/edges.md
> +: When executed, the update expression of the edge is evaluated. The side effect of this expression changes the state of the system.
```suggestion
: When an edge is traversed, the update expression of the edge is evaluated. The side effect of this expression changes the state of the system.
```

2023-06-02 10:59 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +`{ x<=5, Gate.Idle, Gate.Occ }: A[] safe`
Good catch!

2023-06-06 10:45 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +`{ x<=5, Gate.Idle, Gate.Occ }: A[] safe`
This query type does not work in Uppaal 5 it throws a segmentation fault when trying

2023-06-21 15:29 UTC, merged