Expanded documentation about observability in learning queries
UPPAALModelChecker/docs.uppaal.org pull request #46
Opened 2023-11-22 15:20 UTC by thorulf4

2023-11-23 13:37 UTC, mikucionisaau requested changes
I think this is hopeless: you've added more text, but barely more information.
I think we should write a separate long page about learning queries, methods and parameters (and then refer to this page for syntax, where elements are explained only briefly).

2023-11-23 13:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +: learns a strategy that minimizes the expected `cost` value within `10` time units or when `goal` predicate becomes true. Where only the expressions `i`, `j`, `d` and `f` are observable by the learn
`learning agent` is undefined (also it does not add any new information, just confuses).
`entire state space` is wrong, should be `entire state`.

2023-11-23 13:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +<br>There are two types of observability, Discrete- and Continouos- observability. These are distinquished by what brackets expressions are put into i.e. `{discrete expressions} -> {continouos expres
```suggestion
<br>There are two types of observable state expressions: discrete and continuous. Discrete are specified in the first bracket and the continuous in the second: `{discrete expressions} -> {continouos expressions}`.
```

2023-11-23 13:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +Any expressions here will be observable by the learning agent i.e given the learning query `minE(cost) [<=10] { i, j } -> { } : <> goal` the learning agent will only be able to create a strategy for
This does not add any information. Also `all combinations` is misleading: it will construct a mapping which contains only the observed values.

2023-11-23 13:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +
`online partial refinement` is undefined. Also it is very specific (relates to specific learning methods), whereas UPPAAL supports many methods.

2023-11-29 09:35 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +Any expressions here will be observable by the learning agent i.e given the learning query `minE(cost) [<=10] { i, j } -> { } : <> goal` the learning agent will only be able to create a strategy for
Removed `all combinations` and cut down on bloat.

2023-11-29 09:39 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +
I meant `online partition refinement`, but I don't think you can change how continuous expressions are discretized in Uppaal.

I thought citing a paper would suffice as a definition is out of scope for this documentation.
Although the other option is to remove the mention of how we discretize as mentioning it here may only be distracting

2023-11-29 09:41 UTC, thorulf4 commented
> I think we should write a separate long page about learning queries, methods and parameters (and then refer to this page for syntax, where elements are explained only briefly).
I completely agree that we need to expand on learning documentation, but that will take some time and this was meant to be quick update since Kim asked for it

2023-11-29 10:37 UTC, mikucionisaau requested changes
Some rephrasing:
1) one sentence per line helps with version control (the single line-break is not visible in HTML)
2) use present tense instead of future or past.

2023-11-29 10:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +: learns a strategy that minimizes the expected `cost` expression within `10` time units or when `goal` predicate becomes true. Where only the expressions `i`, `j`, `d` and `f` are observable.  The `
```suggestion
: learns a strategy that minimizes the expected `cost` expression within `10` time units or when `goal` predicate becomes true. Where only the expressions `i`, `j`, `d` and `f` are observable.  The `{..} -> {..}` syntax controls what is observable. 
On one hand, by observing only a partial state learning times can be significantly reduced and the strategy structure simplified. On the other hand, the expected value can be far from optimum if outcomes do not depend on the observed state.
There are two types of observable state expressions: *discrete* and *continuous*. 
The *discrete* are specified in the first bracket and the *continuous* in the second: `{discrete expressions} -> {continuous expressions}`. 
By default the entire state is considered during learning.
```

2023-11-29 10:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +**Discrete** expressions will be observable as is i.e the query `minE(cost) [<=10] { i, j } -> { } : <> goal` the will create a strategy by only observing `i` and `j` values.
```suggestion
**Discrete** expressions are observed as they are, i.e the query `minE(cost) [<=10] { i, j } -> { } : <> goal` creates a strategy by only observing the values of `i` and `j`.
```

2023-11-29 10:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +**Continuous** expressions will be discretized during learning using online partition refinement (see [Teaching Stratego to Play Ball](https://vbn.aau.dk/ws/files/378436068/main.pdf)). The query `min
I am not confident with is meant here
```suggestion
**Continuous** expression values are grouped using online partition refinement (see [Teaching Stratego to Play Ball](https://vbn.aau.dk/ws/files/378436068/main.pdf)). 
The query `minE(cost) [<=10] { } -> { d, f } : <> goal` learns a strategy based on the partitioned values of expressions `d` and `f`.
```

2023-11-29 10:37 UTC, mikucionisaau commented on content/language-reference/requirements-specification/_index.md
> +Process locations will be ignored when specifying observability unless explicitly specified using the expression `Cat.location` and `Mouse.location` where `Cat` and `Mouse` are processes
```suggestion
Process locations are ignored when specifying observability unless explicitly specified using `location` keyword.
For example `Cat.location` and `Mouse.location` refer to the locations of `Cat` and `Mouse` processes.
```

2023-11-29 13:29 UTC, thorulf4 commented on content/language-reference/requirements-specification/_index.md
> +**Continuous** expressions will be discretized during learning using online partition refinement (see [Teaching Stratego to Play Ball](https://vbn.aau.dk/ws/files/378436068/main.pdf)). The query `min
I have a preference towards the discretization wording, but i've improved the sentence according to other comments

2023-11-30 13:33 UTC, merged